[2024-04-13T12:54:22.076+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-13T12:54:22.131+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Process_W3_Data.insert_data_into_db manual__2024-04-13T12:53:29.193444+00:00 [queued]>
[2024-04-13T12:54:22.152+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Process_W3_Data.insert_data_into_db manual__2024-04-13T12:53:29.193444+00:00 [queued]>
[2024-04-13T12:54:22.152+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-13T12:54:22.193+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): insert_data_into_db> on 2024-04-13 12:53:29.193444+00:00
[2024-04-13T12:54:22.206+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=56382) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-13T12:54:22.209+0000] {standard_task_runner.py:63} INFO - Started process 56384 to run task
[2024-04-13T12:54:22.217+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Process_W3_Data', 'insert_data_into_db', 'manual__2024-04-13T12:53:29.193444+00:00', '--job-id', '270', '--raw', '--subdir', 'DAGS_FOLDER/w3c.py', '--cfg-path', '/tmp/tmpvoahghwp']
[2024-04-13T12:54:22.222+0000] {standard_task_runner.py:91} INFO - Job 270: Subtask insert_data_into_db
[2024-04-13T12:54:22.334+0000] {task_command.py:426} INFO - Running <TaskInstance: Process_W3_Data.insert_data_into_db manual__2024-04-13T12:53:29.193444+00:00 [running]> on host 426f0b9f9d71
[2024-04-13T12:54:22.565+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Process_W3_Data' AIRFLOW_CTX_TASK_ID='insert_data_into_db' AIRFLOW_CTX_EXECUTION_DATE='2024-04-13T12:53:29.193444+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-13T12:53:29.193444+00:00'
[2024-04-13T12:54:22.568+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-13T12:54:22.592+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-04-13T12:54:40.015+0000] {w3c.py:72} INFO - Data inserted successfully.
[2024-04-13T12:54:40.016+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-13T12:54:40.017+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-13T12:54:40.052+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=Process_W3_Data, task_id=insert_data_into_db, execution_date=20240413T125329, start_date=20240413T125422, end_date=20240413T125440
[2024-04-13T12:54:40.116+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-13T12:54:40.195+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-13T12:54:40.204+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
