[2024-04-12T16:13:21.804+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-12T16:13:21.832+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Process_W3_Data.insert_data_into_db manual__2024-04-12T16:12:31.911827+00:00 [queued]>
[2024-04-12T16:13:21.843+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Process_W3_Data.insert_data_into_db manual__2024-04-12T16:12:31.911827+00:00 [queued]>
[2024-04-12T16:13:21.843+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-12T16:13:21.860+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): insert_data_into_db> on 2024-04-12 16:12:31.911827+00:00
[2024-04-12T16:13:21.872+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=40644) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-12T16:13:21.875+0000] {standard_task_runner.py:63} INFO - Started process 40646 to run task
[2024-04-12T16:13:21.875+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Process_W3_Data', 'insert_data_into_db', 'manual__2024-04-12T16:12:31.911827+00:00', '--job-id', '248', '--raw', '--subdir', 'DAGS_FOLDER/w3c.py', '--cfg-path', '/tmp/tmpr_tw0f66']
[2024-04-12T16:13:21.880+0000] {standard_task_runner.py:91} INFO - Job 248: Subtask insert_data_into_db
[2024-04-12T16:13:21.949+0000] {task_command.py:426} INFO - Running <TaskInstance: Process_W3_Data.insert_data_into_db manual__2024-04-12T16:12:31.911827+00:00 [running]> on host 426f0b9f9d71
[2024-04-12T16:13:22.078+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Process_W3_Data' AIRFLOW_CTX_TASK_ID='insert_data_into_db' AIRFLOW_CTX_EXECUTION_DATE='2024-04-12T16:12:31.911827+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-12T16:12:31.911827+00:00'
[2024-04-12T16:13:22.081+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-12T16:13:22.093+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-04-12T16:13:37.195+0000] {w3c.py:72} INFO - Data inserted successfully.
[2024-04-12T16:13:37.196+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-12T16:13:37.197+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-12T16:13:37.210+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=Process_W3_Data, task_id=insert_data_into_db, execution_date=20240412T161231, start_date=20240412T161321, end_date=20240412T161337
[2024-04-12T16:13:37.247+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-12T16:13:37.268+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-12T16:13:37.270+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
